version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-ajclaims
    ports:
      - "5066:5432"
    environment:
      POSTGRES_DB: new_employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-ajclaims
    ports:
      - "3099:3099"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin123
      PGHOST: postgres
      PGDATABASE: new_employee_db
      PGPORT: 5432

  frontend:
    build: ./Frontend
    container_name: frontend-ajclaims
    ports:
      - "9070:80"

  hr_page:
    build: ./HR_Page
    container_name: hr_page_aj-claims
    ports:
      - "9071:80"

volumes:
  postgres_data:

